apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-application
  template:
    metadata:
      labels:
        app: example-application
    spec:
      containers:
      - name: example-application
        image: docker.io/danblanco/example-application:v4.1.0
        env:
          - name: api_key
            value: "my-secret-key (pretend its from a secret and not hard-coded here!)"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-application
spec:
  type: LoadBalancer
  selector:
    app: example-application
  ports:
  - port: 8080
