apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - image-updater.yaml
images:
  - name: docker.io/danblanco/example-application
    newTag: v4.10.2
